import { PickType } from '@nestjs/swagger';

import { BaseVenueResDto } from './base-venue.res.dto';

export class VenueResDto extends PickType(BaseVenueResDto, [
  'id',
  'created',
  'updated',
  'name',
  'avatarVenue',
  'image',
  'city',
  'address',
  'description',
  'averageCheck',
  'categories',
  'isActive',
  'isModerated',
  'hasWiFi',
  'hasParking',
  'liveMusic',
  'petFriendly',
  'hasTerrace',
  'smokingAllowed',
  'cardPayment',
  'tags',
  'ratingAvg',
  'ratingCount',
  'isLiked',
  'likesCount',
  'user',
  'isFavorite',
  'phone',
  'email',
  'website',
  'socials',
  'menu',
  'workingHours',
]) {}
