export enum VenueCategoryEnum {
  RESTAURANT = 'restaurant',
  BAR = 'bar',
  CAFE = 'cafe',
  PUB = 'pub',
  CLUB = 'club',
  FAST_FOOD = 'fast_food',
  PIZZERIA = 'pizzeria',
  SUSHI = 'sushi',
  BREWERY = 'brewery',
  LOUNGE = 'lounge',
  STEAKHOUSE = 'steakhouse',
  BAKERY = 'bakery',
  COFFEE_SHOP = 'coffee_shop',
  WINE_BAR = 'wine_bar',
  FOOD_COURT = 'food_court',
  STREET_FOOD = 'street_food',
  KARAOKE = 'karaoke',
  HOOKAH = 'hookah',
}
