const baseUrl = process.env.REACT_APP_API_URL || 'http://localhost:3001';

const urls = {
    auth: {
        signUp: `${baseUrl}/auth/sign-up`,
        signIn: `${baseUrl}/auth/sign-in`,
        refresh: `${baseUrl}/auth/refresh`,
        signOut: `${baseUrl}/auth/sign-out`,
        oauth: `${baseUrl}/auth/oauth`,
        verifyEmail: (token: string) => `${baseUrl}/auth/verify-email?token=${token}`,
        resendVerification: `${baseUrl}/auth/resend-verification`,
    },
    venue: {
        base: `${baseUrl}/venues`,
        venueById: (id: string) => `${baseUrl}/venues/${id}`,
        create: `${baseUrl}/venues`,
        update: (id: string) => `${baseUrl}/venues/${id}`,
        delete: (id: string) => `${baseUrl}/venues/${id}`,
        uploadPhoto: `${baseUrl}/venues/upload-photo`,
    },
    tag: {base: `${baseUrl}/tags/popular`},
    news: {base: `${baseUrl}/news`},
    newsVenue: {
        base: (venueId: string) => `${baseUrl}/venues/${venueId}/news`,
        update: (newsId: string) => `${baseUrl}/news/${newsId}`,
        delete: (newsId: string) => `${baseUrl}/news/${newsId}`,
        setActive: (newsId: string) => `${baseUrl}/news/${newsId}/active`,
        setPaid: (newsId: string) => `${baseUrl}/news/${newsId}/paid`,
    },
    top: {base: `${baseUrl}/top/categories`},
    search: {base: `${baseUrl}/search/venue`},
    categories: {
        base: `${baseUrl}/categories`,
        categoryById: (id: string) => `${baseUrl}/categories/${id}`,
    },
    rating: {
        set: (venueId: string) => `${baseUrl}/venues/${venueId}/rating`,
        remove: (venueId: string) => `${baseUrl}/venues/${venueId}/rating`,
    },
    favorites: {
        add: (venueId: string) => `${baseUrl}/venues/${venueId}/favorite`,
        remove: (venueId: string) => `${baseUrl}/venues/${venueId}/favorite`,
        myList: `${baseUrl}/users/me/favorites`,
    },
    likes: {
        add: (venueId: string) => `${baseUrl}/venues/${venueId}/like`,
        remove: (venueId: string) => `${baseUrl}/venues/${venueId}/like`,
    },
    contact: {
        manager: (venueId: string) => `${baseUrl}/venues/${venueId}/contact`,
    },
    complaint: {
        create: (venueId: string) => `${baseUrl}/venues/${venueId}/complaints`,
    },
    comments: {
        list: (venueId: string) => `${baseUrl}/venues/${venueId}/comments`,
        create: (venueId: string) => `${baseUrl}/venues/${venueId}/comments`,
        update: (commentId: string) => `${baseUrl}/comments/${commentId}`,
        delete: (commentId: string) => `${baseUrl}/comments/${commentId}`,
        uploadCheck: `${baseUrl}/upload-check`,
    },
    users: {
        me: `${baseUrl}/users/me`,
        updateMe: `${baseUrl}/users/me`,
        deleteMe: `${baseUrl}/users/me`,
        changePassword: `${baseUrl}/users/me/password`,
        myComments: `${baseUrl}/users/me/comments`,
        myRatings: `${baseUrl}/users/me/ratings`,
        myFavorites: `${baseUrl}/users/me/favorites`,
        uploadAvatar: `${baseUrl}/users/me/avatar`,
        deleteAvatar: `${baseUrl}/users/me/avatar`,
        publicById: (id: string) => `${baseUrl}/users/${id}`,
        followAdd: (id: string) => `${baseUrl}/users/${id}/follow`,
        followRemove: (id: string) => `${baseUrl}/users/${id}/follow`,
        isFollowed: (id: string) => `${baseUrl}/users/${id}/is-followed`,
        myFollowers: `${baseUrl}/users/me/followers`,
        myFollowing: `${baseUrl}/users/me/following`,
        criticAdd: `${baseUrl}/users/me/critic`,
        criticRemove: `${baseUrl}/users/me/critic`,
        venueAdminAdd: `${baseUrl}/users/me/venue-admin`,
        venueAdminRemove: `${baseUrl}/users/me/venue-admin`,
    },
    pyachok: {
        venueList: (venueId: string) => `${baseUrl}/venues/${venueId}/pyachok`,
        create: (venueId: string) => `${baseUrl}/venues/${venueId}/pyachok`,
        myList: `${baseUrl}/users/me/pyachok`,
        feed: `${baseUrl}/pyachok/feed`,
        update: (id: string) => `${baseUrl}/pyachok/${id}`,
        close: (id: string) => `${baseUrl}/pyachok/${id}/close`,
        closeAny: (id: string) => `${baseUrl}/pyachok/${id}/close-any`,
        delete: (id: string) => `${baseUrl}/pyachok/${id}`,
        deleteAny: (id: string) => `${baseUrl}/pyachok/${id}/force`,
    },
    messages: {
        send: (recipientId: string) => `${baseUrl}/messages/to/${recipientId}`,
        inbox: `${baseUrl}/messages/inbox`,
        sent: `${baseUrl}/messages/sent`,
        unreadCount: `${baseUrl}/users/me/messages/unread-count`,
        markRead: (id: string) => `${baseUrl}/messages/${id}/read`,
        markAllRead: `${baseUrl}/messages/read-all`,
        delete: (id: string) => `${baseUrl}/messages/${id}`,
        dialog: (userId: string) => `${baseUrl}/messages/dialog/${userId}`,
    },
    analytics: {
        viewsSummary: (venueId: string) => `${baseUrl}/venues/${venueId}/analytics/views/summary`,
        viewsTimeseries: (venueId: string) => `${baseUrl}/venues/${venueId}/analytics/views/timeseries`,
    },
    admin: {
        venues: `${baseUrl}/admin/venues`,
        pendingVenues: `${baseUrl}/admin/venues/pending`,
        moderateVenue: (id: string) => `${baseUrl}/admin/venues/${id}/moderate`,
        toggleActive: (id: string) => `${baseUrl}/admin/venues/${id}/active`,
        updateVenue: (id: string) => `${baseUrl}/admin/venues/${id}`,
        deleteVenue: (id: string) => `${baseUrl}/admin/venues/${id}`,
        users: `${baseUrl}/admin/users`,
        updateUser: (id: string) => `${baseUrl}/admin/users/${id}`,
        deleteUser: (id: string) => `${baseUrl}/admin/users/${id}`,
        complaints: `${baseUrl}/admin/complaints`,
        complaintById: (id: string) => `${baseUrl}/admin/complaints/${id}`,
        complaintStatus: (id: string) => `${baseUrl}/admin/complaints/${id}/status`,
        topCategories: `${baseUrl}/admin/top/categories`,
        topCategory: (id: string) => `${baseUrl}/admin/top/categories/${id}`,
        topCategoryVenues: (id: string) => `${baseUrl}/admin/top/categories/${id}/venues`,
        topCategoriesOrder: `${baseUrl}/admin/top/categories/order`,
        topCategoryVenueOrder: (id: string) => `${baseUrl}/admin/top/categories/${id}/venues/order`,
        removeTopVenue: (catId: string, venueId: string) => `${baseUrl}/admin/top/categories/${catId}/venues/${venueId}`,
        viewsSummary: (venueId: string) => `${baseUrl}/admin/analytics/venues/${venueId}/views/summary`,
        viewsTimeseries: (venueId: string) => `${baseUrl}/admin/analytics/venues/${venueId}/views/timeseries`,
        deleteComment: (id: string) => `${baseUrl}/admin/comments/${id}`,
        updateComment: (id: string) => `${baseUrl}/admin/comments/${id}`,
        allComments: `${baseUrl}/admin/comments`,
        changeOwner: (id: string) => `${baseUrl}/admin/venues/${id}/owner`,
        setRating: (id: string) => `${baseUrl}/admin/venues/${id}/rating`,
        deleteRating: (venueId: string, userId: string) => `${baseUrl}/admin/venues/${venueId}/rating/${userId}`,
        settings: `${baseUrl}/admin/settings`,
        settingsPublic: `${baseUrl}/admin/settings/public`,
    },
};

export {baseUrl, urls};